### ISSUE TITLE
Test de MutTesting : "Invalid xml given" or "The "-c" option does not exist."

### ISSUE THREAD

**Issue by Bacteries** [Halleck45/MutaTesting#2]
Hi,
I tried MutaTesting but have somme issue installing and using it : 
- First time composer told me "halleck45/mutatesting dev-master requires sebastian/diff 1.0._@dev -> no matching package found." (I added the package "sebastian/diff": "1.0._@dev" in my composer.json to solve this)
- I have issues with "autoload.php" (I hack the bin/mutatesting to solve it)
- Then when I try to use it like :
  `php bin/mutatesting atoum vendor/atoum/atoum/bin/atoum library/DYB/Tests/Units/MyTests.php`
  it give me "Invalid xml given"
- So I try to use `php bin/mutatesting atoum php vendor/atoum/atoum/bin/atoum -c library/DYB/Tests/Units/config.php -f library/DYB/Tests/Units/MyTests.php`
  and I have the "The "-c" option does not exist." error
- Same with `php bin/mutatesting atoum "php vendor/atoum/atoum/bin/atoum -c library/DYB/Tests/Units/config.php" library/DYB/Tests/Units/MyTests.php`

**Comment by Halleck45** [comment]
You need to use the `--options` option :

```
̀./bin/mutatesting phpunit phpunit.phar  atoum php vendor/atoum/atoum/bin/atoum myTestFolder --options="-c library/DYB/Tests/Units/config.php"
```

**Comment by omansour** [comment]
Same issue for me 

Running 

```
./vendor/bin/mutatesting atoum ./vendor/bin/atoum src/M6/Bundle/Player/CoreBundle/Tests/Units/
```

gave me 

```
[UnexpectedValueException]
Invalid xml given
```

no clue to look forward

**Comment by Halleck45** [comment]
I'm on this issue :) . i'll add more verbosity in errors

**Comment by omansour** [comment]
any news ?  :)

**Comment by Halleck45** [comment]
This week-end I think ;)

**Comment by Halleck45** [comment]
Can you try again please, and give me the error message ?

**Comment by omansour** [comment]
Sorry ! I Will do that asap

**Comment by omansour** [comment]
that was an issu on my side :) you can close this issue. Having an explicit error help a lot !
